qntm/greenery

- greenery/fsm.py
Python's pickling did not work on FSM objects. I did not dig too
much into it, but this made pickling work.  My guess so far is that
the old code overwrote greenery.fsm.anything_else, which makes the
class definition unavailable after the import (and when
pickling/unpickling).
> rename class anything_else to allow pickling

- greenery/lego.py
- greenery/lego_test.py
The idea is to not wait till the very end with reducing, because the way
that the equations are solved leads to very complex *repeated* lego
pieces, that then have to be reduced in many many different places of the final result.
Instead, repeatedly reduce after the substitutions to prevent the
complexity from piling up.
Sorry, this is a bit of a drive-by pull request, hope that was ok! Saw the project, found it super interesting and habitually looked at the issues...
> fix issue #43: improve performance of from_fsm

- greenery/fsm.py
- greenery/fsm_test.py
When concatenating fsms with differing alphabets, symbols from the others' alphabets do not map as if they were anything_else.
For example:
```
fsm1=fsm(
alphabet={"a",anything_else},
states={0,1},
initial=0,
finals={1},
map={0:{anything_else:1}}
fsm2=fsm(
alphabet={anything_else},
states={0,1},
initial=0,
finals={1},
map={0:{anything_else:1}}
)
assert (fsm1+fsm2).accepts("ba") # Fails
```
Looking at the concatenated result,
```
>>> print(fsm1+fsm2)
name final? a anything_else 
------------------------------
* 0    False    1             
1    False    2             
2    True                   
```
We see that "a" which is not in fsm2's alphabet does not get treated as if it were anything_else as it should.
To fix this, we check to see if the character is not in the alphabet and create …
> fix concatenation of anything_else

- greenery/fsm.py
- greenery/lego.py
- greenery/lego_test.py
The main benefit of using the more established convention `@dataclass(frozen=True)` and `object.__setattr__(self, "attribute", set(self.attibute))` instead of the current `self.__dict__["attribute" ] = attribute` is it allows for better static inspection by IDEs like PyCharm and VSCode.
This only took me an hour of work, so I'm fine you reject this MR because if this type of code feels unnatural to you and/or if you don't use an IDE.
I'm also happy to discuss this MR further if you'd like more explanation behind this MR.
> Use frozen dataclasses and type annotations

- greenery/lego.py
- greenery/lego_test.py
Found an additional simplification rule during a course project! I _think_ this is as specific as it can get:
If R's language is a subset of S's, then R{a,b}S{c,inf} reduces to R{a}S{c,inf} and S{c,inf}R{a,b} reduces to S{c,inf}R{a}.
For instance, \d+\w+ reduces to \d\w+, and [ab]+a? reduces to [ab]+.
Adding the rule I put in lego.py makes the four tests I added in lego_test pass and does not make any other tests fail.
[also, huge fan of There Is No Antimemetics Division -- I have a copy!]
> added a reduction rule for concs of mults

- greenery/lego.py
- greenery/lego_test.py
Follows #62.
* Add a few more unit tests, including tests for the cases specifically suggested in that PR's leading comment.
* Instead of looping over all the `mult`s in a `conc` twice (once for the R >= S and R <= S tests, once for the R = S test), do it once, binding the mults to `r` and `s` at the start of the loop body.
* Split loop which handles R >= S and R <= S up into two distinct loops. This is a completely subjective change, but in my opinion this is a more readable and it makes some other simplifications possible.
* Move the test for when R = S to be *above* the newly-added test for when R >= S or R <= S - otherwise we end up reducing this `conc` twice for no real reason.
* Move the expensive test for R >= S or R <= S to be before the relatively cheap bounds tests.
* Add an …
> Simplify `mult` collapsing behaviour

- greenery/rxelems.py
- greenery/rxelems_test.py
The `@call_fsm` decorator only works for methods which return a FSM, however this method returns a boolean.
This is a bugfix that existed in v3 and has been rebased because it still exists in V4. It includes a test which exercises the previously unexercised method.
> fix: rxelems.isdisjoint: incorrect use of `@call_fsm` on boolean method

- greenery/parse.py
- greenery/parse_test.py
Open/negated charclass predicates like `\W` and `\S` were combined incorrectly.
They were interpreted as as `not (whitespace or digits)` but their correct interpretation is `(not whitespace) or (not digits)`.
This fixes the misinterpretation and the test. It includes a couple minor nits that made it easier to rebase the fix.
Although I didn't include as a test in this PR because there are plausible reasons that the test suite doesn't already do this, I verified the behaviour against the built-in `re` module with:
```py
import re
from greenery import parse
def test_expr(expr, value):
pat = parse(expr)
rx = re.compile(expr)
assert bool(rx.match(value)) == bool(pat.matches(value))
for expr in (r"\S\D", r"1\D", r"1\D\S"):
for negation in (True, False):
for value in "12x ":
test_expr(f'[{"^" …
```
> fix incorrect combination of open charclass predicates

- greenery/conc_test.py
- greenery/fsm_test.py
- greenery/multiplier_test.py
- greenery/parse_test.py
- greenery/rxelems_test.py
Clearer than the previous pattern of catching `AssertionError` and then re-asserting `False`, and provides better stack traces.
This also improves a few of those tests to match on specific exception messages, since the exceptions are not currently typed in most cases.
> test/style: use `pytest.raises` vs `except: …`/`assert False`

- greenery/fsm.py
- greenery/fsm_test.py
- greenery/rxelems.py
- greenery/rxelems_test.py
Although the classes here return specialised instances from `__reverse__`, `reversed()` itself may be an object which delegates to that iterable, in the same way that e.g. `map()` or `enumerate()` does.
This rightly causes linters to complain that `reversed()` doesn't return a `Pattern`, etc, as assumed by some parts of the code.
This preserves the existing iterable `__reversed__` dunder method, but internally updates to use `.reversed()` whenever the container type is required to be consistent.
> types: `reversed()` builtin is only typed to return an `Iterator`

- greenery/fsm.py
- greenery/fsm_test.py
Previously the `Fsm` constructor did not validate that transition sources were in `states` or that that the symbols were in `alphabet`.
Since neither is inferred from the transition map, nor is it inferred from them, it was possible to construct an `Fsm` in which iterating over `self.map` would give values inconsistent with those sets.
This is arguably unnecessary work, but seemed inconsistent and likely just overlooked since validations exist for the destination states, the initial state, and terminals states.
This PR includes tests written in the current style, however I have a resolution for #70 prepared depending on preferred merge order.
> fsm: validate transition source and symbols

- .github/workflows/workflow-1.yml
- .isort.cfg
- README.md
- greenery/__init__.py
- greenery/bound.py
- greenery/bound_test.py
- greenery/charclass.py
- greenery/charclass_test.py
- greenery/conc_test.py
- greenery/fsm.py
- greenery/fsm_test.py
- greenery/mult_test.py
- greenery/multiplier.py
- greenery/multiplier_test.py
- greenery/parse.py
- greenery/parse_test.py
- greenery/pattern_test.py
- greenery/rxelems.py
- greenery/rxelems_test.py
- main.py
- setup.py
This PR modernizes import/export style a bit.
The main thrust is:
1. Remove the python 2-era `coding: utf8` header. Not needed in Python 3.
2. Prepend `from __future__ import annotations` to the modules. Safe, improves performance, and allows more modern types (not included here).
3. Adds `isort` to sort the imports automatically, and makes those imports all consistent. Includes update to the `workflow.yaml`.
4. Adds explicit symbol exports via `__all__` to each of the modules.
> lint: consistent import order with `isort`, add explicit `__all__` exports

- greenery/rxelems.py
Caught by pylint in another one of my branches. There is no "inner" member.
> fix: incorrect `rxelems.Mult` "self.inner" attribute access

- .github/workflows/workflow-1.yml
- .isort.cfg
- README.md
- greenery/__init__.py
- greenery/bound.py
- greenery/bound_test.py
- greenery/charclass.py
- greenery/charclass_test.py
- greenery/conc_test.py
- greenery/fsm.py
- greenery/fsm_test.py
- greenery/mult_test.py
- greenery/multiplier.py
- greenery/multiplier_test.py
- greenery/parse.py
- greenery/parse_test.py
- greenery/pattern_test.py
- greenery/rxelems.py
- greenery/rxelems_test.py
- main.py
- mypy.ini
- setup.py
This adds a very-lenient `mypy.ini` and adds `mypy` to the CI check steps.
It also fixes the bare-minimum of type errors necessary to pass initially, and modernizes the few type annotations present.
Since most of the code is unannotated, type-checking is skipped for most of it, hence the leniency.
(I also have this codebase checkable in full-coverage strict mode, but have some experiments to untangle from those branches).
This is based on the same base as #73, since the `from __future__ import annotations` allows the annotations to be more reasonable.
> ci: add `mypy` + minimum type fixes

- greenery/fsm.py
- greenery/fsm_test.py
- greenery/rxelems.py
In greenery v4, `anything_else` was just an instance of a single-use eponymous class.
In #65, it was changed to a fixed random string to address #64
However, that symbol is _not_ a string: it's a special symbol and has special comparison characteristics. It kinda represents the "co-alphabet".
This re-introduces the class instance, but modernizes it and keeps that original bug fixed.
* It's made a singleton enum. This allows type-checkers to automatically refine checks like `if x is ANYTHING_ELSE` without needing casts or `isinstance` checks. It also ensures that unplicking does not make a separate instance.
* The comparison operators are updated to incorporate its special comparison behaviour, eliminating the need to carry an `alphabet_key` helper around.
* Some tests are added to verify …
> fsm: restore type-distinguished `ANYTHING_ELSE`

- greenery/bound.py
- greenery/bound_test.py
- greenery/charclass.py
- greenery/charclass_test.py
- greenery/conc_test.py
- greenery/fsm.py
- greenery/fsm_test.py
- greenery/mult_test.py
- greenery/multiplier.py
- greenery/multiplier_test.py
- greenery/parse.py
- greenery/parse_test.py
- greenery/pattern_test.py
- greenery/rxelems.py
- greenery/rxelems_test.py
- mypy.ini
This turns on all the checking of mypy overall; and then for each file it adds the necessary suppressions. Very heavy-handed, but allows type fixes to be applied independently.
> mypy: enable strict mode using per-file suppression

- .flake8
- .github/workflows/workflow-1.yml
- README.md
- greenery/bound.py
- greenery/charclass.py
- greenery/fsm.py
- greenery/fsm_test.py
- greenery/mult_test.py
- greenery/multiplier.py
- greenery/parse.py
- greenery/rxelems.py
- greenery/rxelems_test.py
NOTE: #80 is based on this branch, and if that merges, this will auto-close.
This consistent-ifies some of the formatting with typical Python styling, incrementally fixing each of the `flake8`/`pycodestyle` warnings until none are left, passing with "all rules on".
(The one remaining suppression of `W503` is disabled-by-default and is required to be disabled for subsequent `black` autoformatting).
This is a lead-in to https://github.com/qntm/greenery/compare/main...rwe:greenery:black which builds on this to introduce fully-automated formatting and https://github.com/qntm/greenery/compare/main...rwe:greenery:pylint which introduces stricter `pylint` linting.
With one small exception, this PR touches only formatting and not logic, structure, or names.
The small exception is this change: …
> lint: fix up strict-ish flake8/pycodestyle formatting

- greenery/charclass.py
- greenery/charclass_test.py
- greenery/parse.py
This fixes the types of the arguments and attributes of `Charclass`.
The constructor now accepts a general `Iterable[str]` and exposes a `frozenset[str]`.
It also raises slightly more-specific `TypeError`/`ValueError` on invalid entries in the supplied set.
This allows `mypy --strict greenery/charclass{_test}.py` to pass.
> Charclass: type signatures and fixed types

- greenery/fsm.py
- greenery/fsm_test.py
- greenery/rxelems_test.py
This gives `Fsm` properly contravariant constructor types, so that the inputs can be general `Iterable[str]` but read-only types are exposed.
It then types all of the methods, so that it passes `mypy --strict greenery/fsm{,_test}.py`.
There are a couple minor fixes, as well:
* `copy()` returns `self`, as `frozenset(…).copy()` does.
* `__eq__` (e.g. `a == "x"`) no longer throws `AttributeError` when compared to a different type.
> fsm: immutability and fixed types

- greenery/bound.py
- greenery/bound_test.py
This adds some basic tests to `bound_test.py`, fixes a bug in `__eq__`, and adds type annotations. This allows `mypy --strict greenery/bound{,_test}.py` to pass.
> Bound: type fixes + some basic missing tests

- greenery/charclass.py
- greenery/charclass_test.py
- greenery/fsm.py
- greenery/parse.py
In #69, the incorrect combination of open (negated) charclasses was fixed in `greenery/parse.py`. The corrected logic was identical to that of bulk union/intersection of `Charclass` objects.
This moves that logic into the `Charclass` class and adds/restores tests around those methods.
> Charclass: bulk union/intersection methods

- .flake8
- .github/workflows/workflow-1.yml
- README.md
- greenery/bound.py
- greenery/charclass.py
- greenery/charclass_test.py
- greenery/conc_test.py
- greenery/fsm.py
- greenery/fsm_test.py
- greenery/mult_test.py
- greenery/multiplier.py
- greenery/multiplier_test.py
- greenery/parse.py
- greenery/parse_test.py
- greenery/pattern_test.py
- greenery/rxelems.py
- greenery/rxelems_test.py
- setup.py
This integrates the [`black` auto-formatter](https://github.com/psf/black#used-by). It updates the formatting incrementally (mainly to assist branch maintenance via git's recursive merge) and then adds it to the CI steps.
Note that this branch is based on the flake8/pycodestyle fixup PR #79, and the narrower difference between them can be viewed here: https://github.com/qntm/greenery/compare/rwe:flake8...rwe:black?expand=1 
If this PR merges first, that one will auto-close.
Although `black`'s formatting rules aren't always what I would want (e.g. its treatment of nested function calls across lines), the benefits of a single "format this" command, e.g. when resolving merges, is quite high. `black` is used very widely in high-profile projects:
* https://github.com/psf/black#used-by
@qntm I …
> ci: integrate black auto-formatter

- greenery/conc_test.py
- greenery/mult_test.py
- greenery/pattern_test.py
- greenery/rxelems.py
- greenery/rxelems_test.py
This allows `mypy --strict greenery/{rxelems,{rxelems,conc,mult,pattern}_test}.py` to pass.
> rxelems.Pattern, Conc, Mult: type fixes

- greenery/parse.py
- greenery/parse_test.py
- greenery/rxelems.py
This makes the result types consistent in matcher helpers in `parse.py`, defines a generic `MatchResult[…]` type, and annotates the functions there.
This is sufficient to pass `mypy --strict greenery/parse{,_test}.py`.
One change was required in `rxelems`, to avoid `untyped-call` errors due to missing annotations on the `Conc` and `Pattern` constructors: that change is also included effectively in #89 and should merge cleanly.
> parse.py + parse_test.py type fixes

- greenery/multiplier.py
- greenery/multiplier_test.py
There should no restriction against the ZERO interval `{0}`:
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap09.html#tag_09_04
> ```
> Interval expression of the format "{m}", "{m,}", or "{m,n}", together
> with that interval expression it shall match what repeated consecutive
> occurrences of the ERE would match. The values of m and n are decimal
> integers in the range 0 <= m<= n<= {RE_DUP_MAX}, where m specifies the
> exact or minimum number of occurrences and n specifies the maximum
> number of occurrences. The expression "{m}" matches exactly m
> occurrences of the preceding ERE, "{m,}" matches at least m
> occurrences, and "{m,n}" matches any number of occurrences between m
> and n, inclusive.
> ```
> Multiplier: allow serializing `{0}`
